# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:


- stage: SonarAnalysis
  jobs:
  - job: Sonarscan
    container:  mercuriete/sonar-scanner:latest
    steps:
     - task: DownloadBuildArtifacts@0
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)' 
     - bash: |
              
 
    
      
     
    
    
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!