apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
 type: NodePort
 ports:
  -port: 8080
   targetPort: 8080
 selector:
   app: hello-world-app
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow-world
spec:
 replicas: 1
 selector:
   matchLabels: hello-world-app
 template:
   metadata:
    labels:
     app: hello-world-app
   spec:
    containers:
      -name: hello-world
       image: kadugon
       ports:
        -containerPort: 8080
     
    

   
