apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
 type: NodePort
 ports:
  - port: 8080
    targetPort: 8080
 selector:
   app: hello-world-app
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
 replicas: 1
 selector:
   matchLabels: 
    app: hello-world-app
 template:
   metadata:
    labels:
     app: hello-world-app
   spec:
    containers:
      - name: hello-world
        image: kadungon/helloworld-app:<VERSION>
        ports:
        - containerPort: 8080
     
    

   
